name: nokosu2023
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  provider: ^6.0.1
  shared_preferences: ^2.2.2
  flutter_inset_box_shadow: ^1.0.8
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  flutter_svg: ^2.0.9
  http: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  dio: ^5.3.3
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  uses-material-design: true
  assets:
    - images/