name: nokosu2023
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  chewie: ^1.5.0
  dio: ^5.2.1
  flutter_riverpod: ^2.2.0
  flutter_lints: ^2.0.0
  image_picker: 1.0.4
  geolocator: ^7.0.3
  geocoding: ^2.1.1
  
  


flutter:
  uses-material-design: true
  generate: true
dependencies:
  camera: ^0.10.5+5
  path: ^1.8.3
  path_provider: ^2.1.1
  video_player: ^2.8.1
